Hi there! This is Shavarsh Melikyan's gradient descent algorithm's implementation (multiple features). This algorithm was learnt through the ML specialization's "Supervized Machine Learning" (part 1: https://www.deeplearning.ai/program/machine-learning-specialization/) course; materials from week #2

In [1]:
#first of all, importing important and useful libraries
import numpy as np
import math, copy
import matplotlib.pyplot as plt

In [6]:
#some arbitrary data of houses' sizes and their prices/bedrooms/rooms/floors

X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(X_train, y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]] [460 232 178]


In [8]:
#function which defines a cost function (which we have to minimize by GD)

def compute_cost(x, y, w, b):
    m = x.shape[0] #number of examples
    cost = 0
    
    
    for i in range(m): #sum of differences' square
        f_wb_i = np.dot(x, w) + b
        cost = cost + (f_wb_i - y[i]) ** 2
        
    total_cost = cost / (2*m) 
    return total_cost

In [9]:
#now writing the function for computing gradients (partial derivatives with respect to w and b of cost function J)

def compute_gradient(x, y, w, b):
    m, n = x.shape #number of examples
    dj_dw = np.zeros((n,))
    dj_db = 0
    
    for i in range(m):                             
        err = (np.dot(x[i], w) + b) - y[i]   
        for j in range(n):                         
            dj_dw[j] = dj_dw[j] + err * x[i, j]    
        dj_db = dj_db + err                        
    dj_dw = dj_dw / m                                
    dj_db = dj_db / m                                
        
    return dj_db, dj_dw

In [10]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [11]:
#Compute and display gradient 
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251122999121e-06
dj_dw at initial w,b: 
 [-2.72623574e-03 -6.27197255e-06 -2.21745574e-06 -6.92403377e-05]


In [12]:
#defining function of the gradient descent which returns w, b and lists of cost function's values 
#and parameter lists ([w, b])

"""

"""

def gradient_descent(x, y, w_in, b_in, alpha, num_iters, cost_function, gradient_function):
    
    w = copy.deepcopy(w_in)
    b = copy.deepcopy(b_in)
    dj_dw = 0
    dj_db = 0
    J_history = []
    p_history = []
    
    for i in range(num_iters):
        dj_dw, dj_db = gradient_function(x, y, w, b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
        
        if i < 10000:
            J_history.append(cost_function(x, y, w, b))
            p_history.append([w, b])
            
        if i% math.ceil(num_iters/10) == 0:
            print(f"Iteration {i:4}: Cost {J_history[-1]:0.2e} ",
                  f"dj_dw: {dj_dw: 0.3e}, dj_db: {dj_db: 0.3e}  ",
                  f"w: {w: 0.3e}, b:{b: 0.5e}")
            
    return w, b, J_history, p_history